/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Alliance__factory } from "./Alliance__factory";
export { Greeter__factory } from "./Greeter__factory";
